language: node_js

node_js:
  - 5.6.0

env:
  global:
    - secure: ptDCXxdoR+MFL29P1eBPo1e9j4hXv8EiN/J7dGP8su6523ZJ23iM+T7PFo4uEnfns/judd2VkNz8Rc3jkKsASdOY6tnbLfRA2TeG5PArJkTuzdmQNPqLShee0+i/FooWNPG2LyTKnoPynCQo2TJNgZc8qZgo+ceMmzIwdf7gCwn1dn8g2ky80yIRZV3rqK4MXb9pR7s2MdTAmRyYyK6klVS0xZ1LXGXdbZiVCrtsZbXPp2W6grvNGOo8Z0inQi/+lbNL+qvcGVw12vcQ3PC/Fyn51mQg+IsXA0h8s0tkxqOdASVEepFMLdJ3J4jQIjlNmHUNE6WS4wwXNaVoMarN3UOcONfpQUA2ydSLzo2RaRlpWluznRQBXTOl786n0BxqOh135CgIinHq67SKW3cmFAMUiHLUapDXLn0hny6JfqwMXx0MrxHTeh+XI3RU6ecHw3zT6yOz22m2jbZCkixo86c6C6ftZRQFCxYIj2GvUkVwQUgW+rDERjMLhy8eaGgpaZsC3hLG2xbzd8WmBPoczJOc2fQrPZVRt1b61CXOlZ48W6vQ+mKxB+YKya6oZpqxCbSDeKxKUstWZ7l3jN9SBNdFLKHdT3+8p+t/r7eNHO34RNkX07aS1Hs3VMQ1vosCS24eRizN0OydZEbcZ1YSE/6biXdnXn1MzCi1rJHodgg=
    - secure: ZPCkAo/BZizYanCU9PkgXAaUpRpkApQxDyqvuePIfkaTu3mZAMEPq5+fl4w0jnk3YcyTiPEvgqA2qBAz4KiOjF3Kjmnp9Iv+54qK5/l43XoRFnU7Q/+kR896z3yZPsVL5gvRFJtZWJPv96bfb+YmFYCLqFrjJClFBb0Gelt0RFcAlWiiTKfwuB1lSwLyS+4K7PChhI2nxZMgbpdzHS2LRLWhvs0wTw1aeyN8omZdXbAruuj2b4NyhfgMLiJMp1+l0VViVoYqW28r8ykNJ1skFA0kAI+mVZEQBEyxCvia9maTsQ9bXP+34FD+XE9B29d8rwBGVgOjnANEnXdRIays8CjVy2S9PseBxXv3UJWXHSXoH5VMNijynwtpVHhYWTkK334qWh3ckyjKhAdinOCfp+KhTZ7/ceokU77t9j1zhZhS9DbaXroyWxCoOMzi2qeDCD/qnP6BHJFK64+nUNUTq0A90+F5YrcWDLttHhJLFX7A9C2Wr+eCm/ZTxNcfvnVWobJyOMATwW+1+nFrCcEfiyMGy7nZYxzZcUqp31IIODvMY0ZF9O61Pr77Ft9xGeXLG8+joA2B8xWfel91yjOJYc3ZDD7VdMdwu0IcIHg+gokoPZcim+vyJ5IOpSeaJTlLAtF4t1PN7IorWAafGYWsUhuUa1SiHpTca/iw7D7w35I=

before_script:
  - npm install -g bower
  - bower install

addons:
  sauce_connect: true

